<?php

namespace AfrikPay\OTPBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthOTPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthOTPRepository extends EntityRepository
{

}