<?php

namespace AfrikPay\OTPBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceOTPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceOTPRepository extends EntityRepository
{

}